--View 1: Sales Details:  What is the detailed sales history of completed orders?
create view vw_sales_details as 
select o.id as order_id,
		o.order_date,
		o.customer_id,
		c.name as customer_name,
		p.name as product_name,
		cg.category,
		oi.quantity,
		oi.unit_price,
		oi.quantity * oi.unit_price as line_total
from orders o join customers c on o.customer_id=c.id
join order_items oi on o.id=oi.order_id
join products p on oi.product_id=p.id
join categories cg on p.category_id=cg.id
where o.status IN ('PAID', 'SHIPPED', 'DELIVERED');

--DROP VIEW IF EXISTS vw_sales_details;
--DROP VIEW vw_sales_details CASCADE;

--View 2: Inventory Status: What is the current inventory status of each product?
create view vw_inventory_status as
with products_sold as (
select oi.product_id,
		sum(oi.quantity) as units_solded
from order_items oi join orders o on o.id=oi.order_id
where o.status IN ('PAID', 'SHIPPED', 'DELIVERED')
group by oi.product_id
),
products_returned as (
select product_id,
		sum(quantity) as units_return
from return_items 
group by product_id
)
select p.id as product_id,
		p.name as product_name,
		c.category,
		p.stock as initial_stock,
		coalesce(ps.units_solded,0) as units_sold,
		coalesce(pr.units_return,0) as units_returned,
		p.stock-coalesce(ps.units_solded,0)+coalesce(pr.units_return,0) as estimated_current_stock
from products p left join products_sold ps on ps.product_id=p.id
left join products_returned pr on pr.product_id=p.id
join categories c on p.category_id=c.id;

--DROP VIEW IF EXISTS vw_inventory_status;

--select * from vw_inventory_status limit 10;

--View 3: Customer_revenue: What is the revenue generated by each customer?
create view vw_customer_revenue as
with customer_orders as (
select o.id,
	o.customer_id,
	sum(oi.quantity*oi.unit_price) as revenue
from orders o join order_items oi on o.id=oi.order_id
where o.status IN ('PAID', 'SHIPPED', 'DELIVERED')
group by o.id, o.customer_id	
)
select c.id as customer_id,
		c.name as customer_name,
		count(co.customer_id) as total_orders,
		coalesce(SUM(co.revenue),0) as total_revenue,
		coalesce(round(avg(co.revenue)::numeric,2),0) as avg_order_value
from customers c left join customer_orders co on c.id=co.customer_id
group by c.id, c.name;


--DROP VIEW IF EXISTS vw_customer_revenue;

--View 4: Category_performance: What is the performance of each product category?
create view vw_category_performance as
with products_info as (
select oi.product_id,
		sum(oi.quantity) as product_quantity,
		sum(oi.quantity*oi.unit_price) as product_revenue
from order_items oi join orders o
on oi.order_id = o.id
where o.status IN ('PAID', 'SHIPPED', 'DELIVERED')
group by oi.product_id
)
select c.category,
		count(p.id) as total_products,
		coalesce(sum(pi.product_quantity),0) as units_sold,
		coalesce(sum(pi.product_revenue),0) as total_revenue,
		round(avg(coalesce(pi.product_revenue,0))::numeric,2) as avg_product_revenue
from products p left join productS_info pi on p.id=pi.product_id
join categories c on p.category_id=c.id
group by c.category;

SELECT *
FROM vw_category_performance
ORDER BY total_revenue DESC;

--View 5: Product_Return_Performance: What is the return performance of each product?
create view vw_product_return_performance as
with returned_product as (
select product_id,
		sum(quantity) as return_product
from return_items
group by product_id
),
sold_products as (
select oi.product_id,
		sum(oi.quantity) as sold_product
from order_items oi join orders o
on oi.order_id = o.id
where o.status IN ('PAID', 'SHIPPED', 'DELIVERED')
group by oi.product_id
)
select p.id as product_id,
		p.name as product_name,
		c.category,
		coalesce(sp.sold_product,0) as sold_units,
		coalesce(rp.return_product,0) as returned_units,
		round((coalesce(rp.return_product,0)*100.0/nullif(coalesce(sp.sold_product,0),0))::numeric, 2) as return_rate
from products p left join returned_product rp on p.id=rp.product_id
left join sold_products sp on p.id=sp.product_id
join categories c on p.category_id=c.id;
		